services:
  postgres:
    image: postgres:latest
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sill
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - net
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - net
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
  app:
    build:
      context: ./
    command: npm run dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    depends_on:
      - postgres
      - redis
    networks:
      - net
    volumes:
      - ${APP_DIR}:/app
      - /app/node_modules
volumes:
  postgres_db:
  redis_data:
networks:
  net:
    driver: bridge
